### ISSUE TITLE
Add single metric for comparison

### ISSUE THREAD

**Issue by ClFeSc** [dkuska/hpi-adp-ind#13]
We should introduce a (ideally) single metric value that describes how "good" a certain experiment, i.e. sampling methods/rates, etc, is, to be able to easily compare multiple experiments.

**Comment by ClFeSc** [comment]
A possible start for this would be #9 (but not sufficient).

**Comment by dkuska** [comment]
The kind of metric is dependent on what we want to investigate.

I would put this on hold until we know where we are going with this project.

**Comment by ClFeSc** [comment]
I think this has been implemented at least by #32.
