### ISSUE TITLE
Rework Experiment Design - Combination of Files/Samples

### ISSUE THREAD

**Issue by dkuska** [dkuska/hpi-adp-ind#17]
In the beginning it was fine to simply build the cross product of each file-version (original, sampled, etc.).

However as we move to column sampling this does not work anymore and will blow up in our face, as the number of experiments to conduct grows exponentially with the number of columns.

We will need to rethink the way we design our experiments and combine columns.

**Comment by ClFeSc** [comment]
Can this be closed? @dkuska
