### ISSUE TITLE
Rework Sampling Strategies

### ISSUE THREAD

**Issue by dkuska** [dkuska/hpi-adp-ind#24]
Instead of applying static sampling strategies and rates, we want to move towards a more dynamic approach, where we sample according to the structure of the data.

1. Sorting of values inside column
2. Keeping only unique values
3. New Sampling Strategies:
3.1 Smallest/Largest (for int type columns)
3.2 Shortest/Longest (for string type columns)

**Comment by ClFeSc** [comment]
Can this be closed? @dkuska
