### ISSUE TITLE
Calculate and save column statistics at runtime

### ISSUE THREAD

**Issue by dkuska** [dkuska/hpi-adp-ind#25]
For result probabilization we need to calculate a number of column statistics and keep them in memory:

1. Range - Minimum & Maximum
2. Mean/Median (TODO: Decide if this is useful somewhere)
3. Value Count - Number of values in column
4. Distinct Count - Number of distinct/unique values

This information will need to be passed on to the evaluation/result consolidation.
As such it may be written to a file or kept in memory during execution.

**Comment by ClFeSc** [comment]
Can this be closed? @dkuska
