### ISSUE TITLE
(Temporarily) disable tuples-to-remove metric

### ISSUE THREAD

**Issue by ClFeSc** [dkuska/hpi-adp-ind#29]
I think we should temporarily disable the tuples to remove metric as it's too slow in the case of the many thousand INDs found with PartialSPIDER. In the long run we should figure out how to improve it or whether we actually need it.

@dkuska @yjojo17 What do you think about this? Do you agree that we should disable it?

**Comment by dkuska** [comment]
Agree, it isn't used at the moment anyway
