### ISSUE TITLE
Use statistics for exclusion of INDs

### ISSUE THREAD

**Issue by ClFeSc** [dkuska/hpi-adp-ind#8]
We should use statistics, e.g. minimum/maximum values, to exclude theoretical possible INDs before testing them. We should still be able to use data without statistics.

**Comment by dkuska** [comment]
SPIDER/BINDER do this by themselves. Not sure what the point of this is tbh....

We should use the statistics to determine suitable sampling strategies for each column and let SPIDER/BINDER do the rest

**Comment by ClFeSc** [comment]
Apart from PartialSPIDER doing that itself, this has since been implemented in #32.
